"""
RIVO Backend — Recommendation & Scenario ORM Models
=====================================================
Two tables:
  recommendation_results  — persisted search result for a user session
  scenarios               — named planning scenarios (transit/housing)
  scenario_results        — computed before/after metrics per scenario

Recommendation scoring weights (tunable defaults from ALGORITHMS.md):
  housing_fit   30%
  commute_fit   25%
  transport_fit 15%
  family_fit    15%
  work_access   10%
  confidence     5%

Scores are stored broken down by component so the UI can display
"Why this home?" without an opaque AI score.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Float, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


class RecommendationResult(Base):
    """
    Persisted recommendation for a specific listing × user-search pair.
    Stores the component scores so explainability is always reproducible
    from data, not re-generated by an LLM.
    """

    __tablename__ = "recommendation_results"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # Session / search identifier (not a user ID — no PII stored)
    session_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    listing_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    provider: Mapped[str] = mapped_column(String(64))

    # ── Scores (0–1 normalised, higher = better) ─────────────────────────────
    score_total: Mapped[Optional[float]] = mapped_column(Float)
    score_housing: Mapped[Optional[float]] = mapped_column(Float)    # 30% weight
    score_commute: Mapped[Optional[float]] = mapped_column(Float)    # 25%
    score_transport: Mapped[Optional[float]] = mapped_column(Float)  # 15%
    score_family: Mapped[Optional[float]] = mapped_column(Float)     # 15%
    score_work_access: Mapped[Optional[float]] = mapped_column(Float) # 10%
    score_confidence: Mapped[Optional[float]] = mapped_column(Float) # 5%

    # ── Computed metrics ──────────────────────────────────────────────────────
    monthly_rent: Mapped[Optional[float]] = mapped_column(Float)
    monthly_maintenance: Mapped[Optional[float]] = mapped_column(Float)
    monthly_transport_cost: Mapped[Optional[float]] = mapped_column(Float)
    monthly_total_cost: Mapped[Optional[float]] = mapped_column(Float)
    housing_burden_pct: Mapped[Optional[float]] = mapped_column(Float)
    transport_burden_pct: Mapped[Optional[float]] = mapped_column(Float)
    cash_burden_pct: Mapped[Optional[float]] = mapped_column(Float)
    commute_minutes_one_way: Mapped[Optional[int]] = mapped_column(Integer)
    monthly_commute_hours: Mapped[Optional[float]] = mapped_column(Float)

    # ── Hard-constraint outcomes ──────────────────────────────────────────────
    passes_rent_budget: Mapped[Optional[bool]] = mapped_column()
    passes_commute_max: Mapped[Optional[bool]] = mapped_column()
    passes_bhk: Mapped[Optional[bool]] = mapped_column()
    passes_family: Mapped[Optional[bool]] = mapped_column()

    # ── Explainability reasons (text generated from data, not LLM) ───────────
    # Stored as pipe-separated reasons e.g. "within budget|commute ok|school nearby"
    why_recommended: Mapped[Optional[str]] = mapped_column(Text)
    why_not_recommended: Mapped[Optional[str]] = mapped_column(Text)

    data_freshness: Mapped[str] = mapped_column(String(32), default="ESTIMATED")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Scenario(Base):
    """
    A named planning scenario for RIVO City.
    Types:
      transit  — add new stops/routes to the network
      housing  — add a new housing site with units and rent
    """

    __tablename__ = "scenarios"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    scenario_type: Mapped[str] = mapped_column(String(32), nullable=False)   # transit|housing
    description: Mapped[Optional[str]] = mapped_column(Text)
    # Scenario parameters serialised as JSON
    parameters_json: Mapped[Optional[str]] = mapped_column(Text)
    # Reference to real data this augments (e.g. "CMRL Phase II")
    base_network: Mapped[Optional[str]] = mapped_column(String(128))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class ScenarioResult(Base):
    """
    Before/after accessibility metrics for a scenario.
    Stored per occupation × geography cell so planners can
    compare worker reach, commute time and affordable area.
    """

    __tablename__ = "scenario_results"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    scenario_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    occupation_key: Mapped[str] = mapped_column(String(64), nullable=False)
    h3_index: Mapped[Optional[str]] = mapped_column(String(20), index=True)

    # Before metrics
    before_worker_reach_30min: Mapped[Optional[int]] = mapped_column(Integer)
    before_worker_reach_45min: Mapped[Optional[int]] = mapped_column(Integer)
    before_worker_reach_60min: Mapped[Optional[int]] = mapped_column(Integer)
    before_affordable_listings: Mapped[Optional[int]] = mapped_column(Integer)
    before_commute_median_min: Mapped[Optional[float]] = mapped_column(Float)

    # After metrics (with scenario applied)
    after_worker_reach_30min: Mapped[Optional[int]] = mapped_column(Integer)
    after_worker_reach_45min: Mapped[Optional[int]] = mapped_column(Integer)
    after_worker_reach_60min: Mapped[Optional[int]] = mapped_column(Integer)
    after_affordable_listings: Mapped[Optional[int]] = mapped_column(Integer)
    after_commute_median_min: Mapped[Optional[float]] = mapped_column(Float)

    computed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
